# Generated by Django 3.2.10 on 2022-05-22 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20220523_0006'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='', verbose_name='hotels')),
                ('des', models.TextField(max_length=500)),
                ('Hotel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pages.hotel')),
            ],
        ),
    ]
