# Generated by Django 3.2.10 on 2022-05-23 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_hotelview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelview',
            name='Hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.hotel'),
        ),
    ]
