# Generated by Django 3.2.10 on 2022-05-24 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_hotelview_hotel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('dec', models.TextField(max_length=150)),
                ('image', models.ImageField(upload_to='pictures/%y/%m/%d')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
