# Generated by Django 3.2.10 on 2022-05-24 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_resto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('dec', models.TextField(max_length=150)),
                ('date', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
